title: Python for MATLAB Programmers
email: andrew@apjanke.net
description: >- 
  An introduction to numeric Python programming for experienced
  MATLAB developers.
baseurl: "/PythonForMatlabProgrammers"
url: "" 
#twitter_username: apjanke
github_username:  apjanke

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
