
chapters = 00-Preface.md 01-Introduction.md 02-Python-Types.md 03-Control-Structures.md 04-Plotting.md 05-Classes.md 06-Ecosystem.md 07-Conclusion.md

PythonForMatlabProgrammers-SinglePage.md: $(chapters)
	cat $(chapters) > PythonForMatlabProgrammers-SinglePage.md

